id: ID5DA4BA1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:49:03+00:00'
last_modified: '2022-06-09T06:34:52.628959+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16594
  title: གསོ་རིག་མན་ངག་མྱོང་བྱང་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    CA96:
      image_group_id: I2PD18060
      title: Volume 1 of gso rig man ngag myong byang phyogs bsgrigs/
      total_pages: 988
      order: 1
      base_file: CA96.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
