id: P007850
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16594
  title: གསོ་རིག་མན་ངག་མྱོང་བྱང་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    fddeb6ef09424cfdaccb0f2e3f1dbf1c:
      image_group_id: I2PD18060
      title: ''
      volume_number: 1
      total_pages: 988
ebook_metadata:
  title: གསོ་རིག་མན་ངག་མྱོང་བྱང་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007850
  cover: cover.jpg
  layers:
  - pagination
