id: P007850
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16594
  title: གསོ་རིག་མན་ངག་མྱོང་བྱང་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    fccfaeb8edd74a188283d53d34e7d38e:
      image_group_id: I2PD18060
      title: Volume 1 of gso rig man ngag myong byang phyogs bsgrigs/
      volume_number: 1
      total_pages: 988
      base_file: v001.txt
ebook_metadata:
  title: གསོ་རིག་མན་ངག་མྱོང་བྱང་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007850
  cover: cover.jpg
  layers:
  - pagination
